import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Zarb Official - Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col font-[batica] bg-[#FAf8F5]">
          {children}
      </body>
    </html>
  );
}
